// ui/src/Navbar.vue
<template>
  <b-navbar :fixed-top="true" class="app-navbar">
    <template slot="brand">
      <b-navbar-item tag="router-link" :to="{ path: './' }" class="brand">
        <span class="brand-mark" aria-hidden="true">
          <b-icon pack="mdi" icon="virtual-reality" size="is-small"/>
        </span>
        <span class="brand-name" translate="no">XBVR</span>
        <span v-if="currentVersion" class="brand-version">{{currentVersion}}</span>
      </b-navbar-item>
    </template>
    <template slot="start">
      <b-navbar-item tag="router-link" :to="{ path: './' }" class="nav-link">
        <b-icon pack="mdi" icon="movie-open-outline" size="is-small" aria-hidden="true"/>
        <span>{{$t('Scenes')}}</span>
      </b-navbar-item>
      <b-navbar-item tag="router-link" :to="{ path: './actors' }" class="nav-link">
        <b-icon pack="mdi" icon="account-multiple-outline" size="is-small" aria-hidden="true"/>
        <span>{{$t('Actors')}}</span>
      </b-navbar-item>
      <b-navbar-item tag="router-link" :to="{ path: './files' }" class="nav-link">
        <b-icon pack="mdi" icon="folder-outline" size="is-small" aria-hidden="true"/>
        <span>{{$t('Files')}}</span>
      </b-navbar-item>
      <b-navbar-item tag="router-link" :to="{ path: './options' }" class="nav-link">
        <b-icon pack="mdi" icon="cog-outline" size="is-small" aria-hidden="true"/>
        <span>{{$t('Options')}}</span>
      </b-navbar-item>
      <b-navbar-item @click="$store.commit('overlay/showQuickFind')" class="nav-link" role="button">
        <b-icon pack="mdi" icon="lightning-bolt-outline" size="is-small" aria-hidden="true"/>
        <span>{{$t('Quick find')}}</span>
        <kbd class="nav-kbd" aria-hidden="true">?</kbd>
      </b-navbar-item>
    </template>
    <template slot="end">
      <b-navbar-item class="theme-toggle-item">
        <button type="button" class="theme-toggle" @click="onToggleTheme"
                :aria-label="theme === 'dark' ? $t('Switch to light mode') : $t('Switch to dark mode')"
                :title="theme === 'dark' ? $t('Switch to light mode') : $t('Switch to dark mode')">
          <b-icon pack="mdi" :icon="theme === 'dark' ? 'white-balance-sunny' : 'weather-night'" size="is-small" aria-hidden="true"/>
        </button>
      </b-navbar-item>
      <b-navbar-item v-if="hasStatus" class="status-area" aria-live="polite">
        <div class="status-chips">
          <div v-if="Object.keys(lastRescanMessage).length !== 0" class="status-chip">
            <span class="status-dot" :class="{ 'is-active': lockRescan }" aria-hidden="true"></span>
            <strong>{{$t('Files')}}</strong>
            <span class="status-msg">{{lastRescanMessage.message}}</span>
          </div>
          <div v-if="Object.keys(lastScrapeMessage).length !== 0" class="status-chip">
            <span class="status-dot" :class="{ 'is-active': lockScrape }" aria-hidden="true"></span>
            <strong>{{$t('Data')}}</strong>
            <span class="status-msg">{{lastScrapeMessage.message}}</span>
          </div>
        </div>
      </b-navbar-item>
    </template>
  </b-navbar>
</template>

<script>
import api from './api'
import { currentTheme, toggleTheme } from './util/theme'

export default {
  data () {
    return {
      currentVersion: '',
      latestVersion: '',
      theme: currentTheme()
    }
  },
  computed: {
    lockRescan () {
      return this.$store.state.messages.lockRescan
    },
    lastRescanMessage () {
      return this.$store.state.messages.lastRescanMessage
    },
    lockScrape () {
      return this.$store.state.messages.lockScrape
    },
    lastScrapeMessage () {
      return this.$store.state.messages.lastScrapeMessage
    },
    hasStatus () {
      return Object.keys(this.lastRescanMessage).length !== 0 ||
        Object.keys(this.lastScrapeMessage).length !== 0
    }
  },
  methods: {
    onToggleTheme () {
      this.theme = toggleTheme()
    }
  },
  mounted () {
    api.get('/options/version-check').json().then(data => {
      this.currentVersion = data.current_version
      this.latestVersion = data.latest_version

      if (data.update_notify && this.currentVersion !== 'CURRENT') {
        this.$buefy.snackbar.open({
          message: `Version ${this.latestVersion} available!`,
          type: 'is-warning',
          position: 'is-bottom-right',
          actionText: this.$t('Download now'),
          indefinite: true,
          onAction: () => {
            window.location = 'https://github.com/LorthulBoldflare/xbvr-reloaded/releases'
          }
        })
      }
    })
  }
}
</script>

<style scoped>
  .brand {
    display: flex;
    align-items: center;
    gap: 0.55rem;
  }

  .brand:hover {
    background: transparent !important;
  }

  .brand-mark {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 2rem;
    height: 2rem;
    border-radius: 9px;
    color: #fff;
    background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 55%, #d946ef 100%);
    box-shadow: 0 2px 8px rgba(99, 102, 241, 0.4);
  }

  .brand-name {
    font-size: 1.2rem;
    font-weight: 800;
    letter-spacing: -0.02em;
    color: var(--xbvr-text, #1c2333);
  }

  .brand-version {
    font-size: 0.68rem;
    font-weight: 600;
    color: var(--xbvr-text-faint, #98a1b6);
    background: var(--xbvr-surface-sunken, #eef0f4);
    border-radius: 999px;
    padding: 0.15em 0.6em;
    margin-left: 0.15rem;
    align-self: center;
  }

  .nav-link {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    margin: 0 0.1rem;
  }

  .nav-kbd {
    font-family: inherit;
    font-size: 0.68rem;
    font-weight: 600;
    line-height: 1;
    color: var(--xbvr-text-faint, #98a1b6);
    background: var(--xbvr-surface-sunken, #eef0f4);
    border: 1px solid var(--xbvr-border, #e3e6ec);
    border-radius: 5px;
    padding: 0.25em 0.45em;
  }

  .theme-toggle-item {
    display: flex;
    align-items: center;
  }

  .theme-toggle {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 2.25rem;
    height: 2.25rem;
    padding: 0;
    border: 1px solid var(--xbvr-border, #e3e6ec);
    border-radius: 999px;
    background: var(--xbvr-surface, #ffffff);
    color: var(--xbvr-text-muted, #64708a);
    cursor: pointer;
    transition: color var(--xbvr-fast, 140ms) var(--xbvr-ease, cubic-bezier(0.2, 0, 0, 1)),
      border-color var(--xbvr-fast, 140ms) var(--xbvr-ease, cubic-bezier(0.2, 0, 0, 1)),
      background-color var(--xbvr-fast, 140ms) var(--xbvr-ease, cubic-bezier(0.2, 0, 0, 1));
  }

  .theme-toggle:hover {
    color: var(--xbvr-primary, #4f46e5);
    border-color: var(--xbvr-primary, #4f46e5);
    background: var(--xbvr-primary-soft, #eef0fe);
  }

  .status-chips {
    display: flex;
    gap: 0.5rem;
    font-size: 0.8rem;
  }

  .status-chip {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    max-width: 22rem;
    padding: 0.3rem 0.7rem;
    border-radius: 999px;
    background: var(--xbvr-surface-sunken, #eef0f4);
    color: var(--xbvr-text-muted, #64708a);
  }

  .status-msg {
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  .status-dot {
    flex: none;
    width: 8px;
    height: 8px;
    border-radius: 999px;
    background: var(--xbvr-border-strong, #cdd2dc);
  }

  .status-dot.is-active {
    background: var(--xbvr-primary, #4f46e5);
    animation: status-pulse 1.2s ease-in-out infinite;
  }

  @keyframes status-pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.35; }
  }

  @media (prefers-reduced-motion: reduce) {
    .status-dot.is-active {
      animation: none;
    }
  }
</style>

// web/src/components/Navbar.tsx
import { useState } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import { getTheme, toggleTheme } from '../theme'
import { useMessagesStore } from '../store/messages'
import { useUIStore } from '../store/ui'
import { useToastStore } from '../store/toasts'
import { useOptionsStorage, useVersionCheck } from '../api/hooks'
import { Popover } from '../components/Popover'
import { MoonIcon, SunIcon } from '../components/icons'

function StatusChip({ label, active, message }: { label: string; active: boolean; message: string }) {
  return (
    <span
      title={message || label}
      className="flex items-center gap-1.5 rounded-full border border-line bg-surface px-2.5 py-1 text-xs text-muted"
    >
      <span className={`h-1.5 w-1.5 rounded-full ${active ? 'animate-pulse bg-ok' : 'bg-line-strong'}`} />
      {label}
    </span>
  )
}

function ActionsMenu() {
  const { data: storage } = useOptionsStorage()
  const queryClient = useQueryClient()
  const trigger = useMutation({
    mutationFn: (name: string) => api.get(`/task/webhook/${name}`),
    onSuccess: () => useToastStore.getState().success('Webhook triggered'),
    onSettled: () => queryClient.invalidateQueries()
  })

  const hooks: { key: string; label: string; configured: boolean }[] = [
    {
      key: 'trigger-import',
      label: 'Trigger external import',
      configured: !!storage?.webhooks?.trigger_external_import?.url
    },
    {
      key: 'refresh-import',
      label: 'Refresh external import',
      configured: !!storage?.webhooks?.refresh_external_import?.url
    }
  ]
  const visible = hooks.filter((h) => h.configured)
  if (visible.length === 0) return null

  return (
    <Popover
      button={
        <>
          Actions <span className="text-muted">▾</span>
        </>
      }
      width="w-56"
      align="right"
    >
      {(close) => (
        <div className="flex flex-col">
          {visible.map((h) => (
            <button
              key={h.key}
              disabled={trigger.isPending}
              onClick={() => {
                trigger.mutate(h.key)
                close()
              }}
              className="rounded px-2 py-1.5 text-left text-sm hover:bg-accent-soft"
            >
              {h.label}
            </button>
          ))}
        </div>
      )}
    </Popover>
  )
}

export function Navbar() {
  const [theme, setThemeState] = useState(getTheme())
  const { data: version } = useVersionCheck()
  const { lockScrape, lockRescan, lastScrapeMessage, lastRescanMessage } = useMessagesStore()
  const openQuickFind = useUIStore((s) => s.openQuickFind)

  const navClass = ({ isActive }: { isActive: boolean }) =>
    `rounded-lg px-3 py-1.5 text-sm font-medium ${isActive ? 'bg-accent-soft text-accent-strong' : 'text-muted hover:text-fg'}`

  return (
    <>
      <header className="sticky top-0 z-30 border-b border-line bg-surface">
        <div className="mx-auto flex max-w-[1600px] items-center gap-2 px-4 py-2">
          <Link to="/" className="mr-2 flex items-center gap-2 text-lg font-bold tracking-tight">
            XBVR
            {version?.current_version && (
              <span className="rounded-full bg-surface-2 px-2 py-0.5 text-[10px] font-normal text-muted">
                {version.current_version}
              </span>
            )}
          </Link>
          <nav className="flex items-center gap-1">
            <NavLink to="/" end className={navClass}>
              Scenes
            </NavLink>
            <NavLink to="/actors" className={navClass}>
              Actors
            </NavLink>
            <NavLink to="/options" className={navClass}>
              Options
            </NavLink>
          </nav>
          <button
            onClick={() => openQuickFind(false)}
            className="ml-2 flex items-center gap-2 rounded-lg border border-line bg-surface-2 px-3 py-1.5 text-sm text-muted hover:border-line-strong"
            title="Quick find (?)"
          >
            Quick find…
            <kbd className="rounded border border-line bg-surface px-1 text-[10px]">?</kbd>
          </button>
          <div className="ml-auto flex items-center gap-2">
            <StatusChip label="Files" active={lockRescan} message={lastRescanMessage} />
            <StatusChip label="Data" active={lockScrape} message={lastScrapeMessage} />
            <ActionsMenu />
            <button
              onClick={() => setThemeState(toggleTheme())}
              className="rounded-lg border border-line bg-surface px-2.5 py-1.5 text-sm hover:border-line-strong"
              title="Toggle light/dark theme"
            >
              {theme === 'dark' ? <SunIcon /> : <MoonIcon />}
            </button>
          </div>
        </div>
      </header>
      {version?.update_notify && version.latest_version && version.latest_version !== version.current_version && (
        <UpdateSnackbar version={version.latest_version} />
      )}
    </>
  )
}

function UpdateSnackbar({ version }: { version: string }) {
  const [dismissed, setDismissed] = useState(false)
  if (dismissed) return null
  return (
    <div className="fixed bottom-4 left-1/2 z-40 flex -translate-x-1/2 items-center gap-3 rounded-lg border border-warn/40 bg-surface px-4 py-2 shadow-xl">
      <span className="text-sm">
        Version <strong>{version}</strong> available!
      </span>
      <a
        href="https://github.com/xbapps/xbvr/releases"
        target="_blank"
        rel="noreferrer"
        className="rounded-lg bg-accent px-3 py-1 text-sm text-white"
      >
        Download now
      </a>
      <button onClick={() => setDismissed(true)} className="text-muted hover:text-fg" aria-label="Dismiss">
        ✕
      </button>
    </div>
  )
}
